import type { Metadata } from "next";
import Theme from "@/app/theme";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Navegador from "@/componentes/footer/Navegador";
import { Box } from "@mui/material";
import { Main } from "next/document";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      
    <Theme>
    <html lang="es">
      <head>
        {/* Aquí puedes incluir elementos <meta>, <link>, etc. */}
      </head>
      <body>
       
        <Box>
          {children}
          <Navegador />
        </Box>
      </body>
    </html>
  </Theme>
     
    
  );
}
