"use client";
import Search from "@/components/busqueda/search";
import Theme from "@/app/theme";
import "@/styles/globals.css";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Navegador from "@/componentes/footer/Navegador";
import { Box } from "@mui/material";
import { Main } from "next/document";
import { Container } from "@mui/material";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [inHome, setInHome] = useState(true);
  const pathname = usePathname();
  const inHome = pathname === "/";
  // useEffect(() => {
  //   setInHome(pathname === "/");
  // }, [pathname]);

  return (
    <Theme>
      <html lang="es">
        <head>{/* Aquí puedes incluir elementos <meta>, <link>, etc. */}</head>
        <body>
          {inHome ? (
            <Box>
              {children}
              <Navegador />
            </Box>
          ) : (
            <Container maxWidth={"sm"}>
              <Search />
              {children}
              <Navegador />
            </Container>
          )}
        </body>
      </html>
    </Theme>
  );
}
